#include "mex.h"
#include "math.h"

/*
 *  H_RECEIVER.c - receive a position and returns the value of the vector field in such position.
 *  Inputs: 
 *  - tP     : position of transmitter
 *  - m      : magnetic transmission vector
 *  - rP     : receiver position
 *  - angles : receiver orientation
 *  Outputs:
 *  - Hfield : strength of magnetic field in receiver position
 */

#define PERTURBAZIONE 0.1e-9

void HMtx_fnc(double HMtx[], double rR[], double rT[], double m[]) {
    HMtx[0] = -M_1_PI * (double) ((-4 * rR[0] + 4 * rT[0]) * m[0] - 3 * m[1] * rR[1] + 3 * m[1] * rT[1] - 3 * m[2] * rR[2] + 3 * m[2] * rT[2]) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.4e1 + 0.5e1 / 0.8e1 * M_1_PI * (double) ((-2 * (int) pow((double) rR[0], (double) 2) + 4 * rR[0] * rT[0] + (int) pow((double) rR[1], (double) 2) - 2 * rR[1] * rT[1] + (int) pow((double) rR[2], (double) 2) - 2 * rR[2] * rT[2] - 2 * (int) pow((double) rT[0], (double) 2) + (int) pow((double) rT[1], (double) 2) + (int) pow((double) rT[2], (double) 2) + PERTURBAZIONE) * m[0] + 3 * (rR[0] - rT[0]) * (-m[1] * rR[1] + m[1] * rT[1] - m[2] * rR[2] + m[2] * rT[2])) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (2 * rR[0] - 2 * rT[0]);
    HMtx[1] = -M_1_PI * (double) ((2 * rR[1] - 2 * rT[1]) * m[0] - 3 * (rR[0] - rT[0]) * m[1]) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.4e1 + 0.5e1 / 0.8e1 * M_1_PI * (double) ((-2 * (int) pow((double) rR[0], (double) 2) + 4 * rR[0] * rT[0] + (int) pow((double) rR[1], (double) 2) - 2 * rR[1] * rT[1] + (int) pow((double) rR[2], (double) 2) - 2 * rR[2] * rT[2] - 2 * (int) pow((double) rT[0], (double) 2) + (int) pow((double) rT[1], (double) 2) + (int) pow((double) rT[2], (double) 2) + PERTURBAZIONE) * m[0] + 3 * (rR[0] - rT[0]) * (-m[1] * rR[1] + m[1] * rT[1] - m[2] * rR[2] + m[2] * rT[2])) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (2 * rR[1] - 2 * rT[1]);
    HMtx[2] = -M_1_PI * (double) ((2 * rR[2] - 2 * rT[2]) * m[0] - 3 * (rR[0] - rT[0]) * m[2]) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.4e1 + 0.5e1 / 0.8e1 * M_1_PI * (double) ((-2 * (int) pow((double) rR[0], (double) 2) + 4 * rR[0] * rT[0] + (int) pow((double) rR[1], (double) 2) - 2 * rR[1] * rT[1] + (int) pow((double) rR[2], (double) 2) - 2 * rR[2] * rT[2] - 2 * (int) pow((double) rT[0], (double) 2) + (int) pow((double) rT[1], (double) 2) + (int) pow((double) rT[2], (double) 2) + PERTURBAZIONE) * m[0] + 3 * (rR[0] - rT[0]) * (-m[1] * rR[1] + m[1] * rT[1] - m[2] * rR[2] + m[2] * rT[2])) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (2 * rR[2] - 2 * rT[2]);
    HMtx[3] = -M_1_PI * (double) ((4 * rR[0] - 4 * rT[0]) * m[0] + 3 * m[1] * rR[1] - 3 * m[1] * rT[1] + 3 * m[2] * rR[2] - 3 * m[2] * rT[2]) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.4e1 + 0.5e1 / 0.8e1 * M_1_PI * (double) ((-2 * (int) pow((double) rR[0], (double) 2) + 4 * rR[0] * rT[0] + (int) pow((double) rR[1], (double) 2) - 2 * rR[1] * rT[1] + (int) pow((double) rR[2], (double) 2) - 2 * rR[2] * rT[2] - 2 * (int) pow((double) rT[0], (double) 2) + (int) pow((double) rT[1], (double) 2) + (int) pow((double) rT[2], (double) 2) + PERTURBAZIONE) * m[0] + 3 * (rR[0] - rT[0]) * (-m[1] * rR[1] + m[1] * rT[1] - m[2] * rR[2] + m[2] * rT[2])) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (-2 * rR[0] + 2 * rT[0]);
    HMtx[4] = -M_1_PI * (double) ((-2 * rR[1] + 2 * rT[1]) * m[0] + 3 * (rR[0] - rT[0]) * m[1]) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.4e1 + 0.5e1 / 0.8e1 * M_1_PI * (double) ((-2 * (int) pow((double) rR[0], (double) 2) + 4 * rR[0] * rT[0] + (int) pow((double) rR[1], (double) 2) - 2 * rR[1] * rT[1] + (int) pow((double) rR[2], (double) 2) - 2 * rR[2] * rT[2] - 2 * (int) pow((double) rT[0], (double) 2) + (int) pow((double) rT[1], (double) 2) + (int) pow((double) rT[2], (double) 2) + PERTURBAZIONE) * m[0] + 3 * (rR[0] - rT[0]) * (-m[1] * rR[1] + m[1] * rT[1] - m[2] * rR[2] + m[2] * rT[2])) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (-2 * rR[1] + 2 * rT[1]);
    HMtx[5] = -M_1_PI * (double) ((-2 * rR[2] + 2 * rT[2]) * m[0] + 3 * (rR[0] - rT[0]) * m[2]) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.4e1 + 0.5e1 / 0.8e1 * M_1_PI * (double) ((-2 * (int) pow((double) rR[0], (double) 2) + 4 * rR[0] * rT[0] + (int) pow((double) rR[1], (double) 2) - 2 * rR[1] * rT[1] + (int) pow((double) rR[2], (double) 2) - 2 * rR[2] * rT[2] - 2 * (int) pow((double) rT[0], (double) 2) + (int) pow((double) rT[1], (double) 2) + (int) pow((double) rT[2], (double) 2) + PERTURBAZIONE) * m[0] + 3 * (rR[0] - rT[0]) * (-m[1] * rR[1] + m[1] * rT[1] - m[2] * rR[2] + m[2] * rT[2])) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (-2 * rR[2] + 2 * rT[2]);
    HMtx[6] = -M_1_PI * (double) (-2 * (int) pow((double) rR[0], (double) 2) + 4 * rR[0] * rT[0] + (int) pow((double) rR[1], (double) 2) - 2 * rR[1] * rT[1] + (int) pow((double) rR[2], (double) 2) - 2 * rR[2] * rT[2] - 2 * (int) pow((double) rT[0], (double) 2) + (int) pow((double) rT[1], (double) 2) + (int) pow((double) rT[2], (double) 2) + PERTURBAZIONE) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.4e1;
    HMtx[7] = -0.3e1 / 0.4e1 * M_1_PI * (double) (rR[0] - rT[0]) * (double) (-rR[1] + rT[1]) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1);
    HMtx[8] = -0.3e1 / 0.4e1 * M_1_PI * (double) (rR[0] - rT[0]) * (double) (rT[2] - rR[2]) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1);
    HMtx[9] = -(double) ((2 * rR[0] - 2 * rT[0]) * m[1] - 3 * (rR[1] - rT[1]) * m[0]) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.4e1 + 0.5e1 / 0.8e1 * (double) (((int) pow((double) rR[0], (double) 2) - 2 * rR[0] * rT[0] - 2 * (int) pow((double) rR[1], (double) 2) + 4 * rR[1] * rT[1] + (int) pow((double) rR[2], (double) 2) - 2 * rR[2] * rT[2] + (int) pow((double) rT[0], (double) 2) - 2 * (int) pow((double) rT[1], (double) 2) + (int) pow((double) rT[2], (double) 2) + PERTURBAZIONE) * m[1] + 3 * (rR[1] - rT[1]) * (-m[0] * rR[0] + m[0] * rT[0] - m[2] * rR[2] + m[2] * rT[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (2 * rR[0] - 2 * rT[0]);
    HMtx[10] = -(double) ((-4 * rR[1] + 4 * rT[1]) * m[1] - 3 * m[0] * rR[0] + 3 * m[0] * rT[0] - 3 * m[2] * rR[2] + 3 * m[2] * rT[2]) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.4e1 + 0.5e1 / 0.8e1 * (double) (((int) pow((double) rR[0], (double) 2) - 2 * rR[0] * rT[0] - 2 * (int) pow((double) rR[1], (double) 2) + 4 * rR[1] * rT[1] + (int) pow((double) rR[2], (double) 2) - 2 * rR[2] * rT[2] + (int) pow((double) rT[0], (double) 2) - 2 * (int) pow((double) rT[1], (double) 2) + (int) pow((double) rT[2], (double) 2) + PERTURBAZIONE) * m[1] + 3 * (rR[1] - rT[1]) * (-m[0] * rR[0] + m[0] * rT[0] - m[2] * rR[2] + m[2] * rT[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (2 * rR[1] - 2 * rT[1]);
    HMtx[11] = -(double) ((2 * rR[2] - 2 * rT[2]) * m[1] - 3 * (rR[1] - rT[1]) * m[2]) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.4e1 + 0.5e1 / 0.8e1 * (double) (((int) pow((double) rR[0], (double) 2) - 2 * rR[0] * rT[0] - 2 * (int) pow((double) rR[1], (double) 2) + 4 * rR[1] * rT[1] + (int) pow((double) rR[2], (double) 2) - 2 * rR[2] * rT[2] + (int) pow((double) rT[0], (double) 2) - 2 * (int) pow((double) rT[1], (double) 2) + (int) pow((double) rT[2], (double) 2) + PERTURBAZIONE) * m[1] + 3 * (rR[1] - rT[1]) * (-m[0] * rR[0] + m[0] * rT[0] - m[2] * rR[2] + m[2] * rT[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (2 * rR[2] - 2 * rT[2]);
    HMtx[12] = -(double) ((-2 * rR[0] + 2 * rT[0]) * m[1] + 3 * (rR[1] - rT[1]) * m[0]) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.4e1 + 0.5e1 / 0.8e1 * (double) (((int) pow((double) rR[0], (double) 2) - 2 * rR[0] * rT[0] - 2 * (int) pow((double) rR[1], (double) 2) + 4 * rR[1] * rT[1] + (int) pow((double) rR[2], (double) 2) - 2 * rR[2] * rT[2] + (int) pow((double) rT[0], (double) 2) - 2 * (int) pow((double) rT[1], (double) 2) + (int) pow((double) rT[2], (double) 2) + PERTURBAZIONE) * m[1] + 3 * (rR[1] - rT[1]) * (-m[0] * rR[0] + m[0] * rT[0] - m[2] * rR[2] + m[2] * rT[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (-2 * rR[0] + 2 * rT[0]);
    HMtx[13] = -(double) ((4 * rR[1] - 4 * rT[1]) * m[1] + 3 * m[0] * rR[0] - 3 * m[0] * rT[0] + 3 * m[2] * rR[2] - 3 * m[2] * rT[2]) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.4e1 + 0.5e1 / 0.8e1 * (double) (((int) pow((double) rR[0], (double) 2) - 2 * rR[0] * rT[0] - 2 * (int) pow((double) rR[1], (double) 2) + 4 * rR[1] * rT[1] + (int) pow((double) rR[2], (double) 2) - 2 * rR[2] * rT[2] + (int) pow((double) rT[0], (double) 2) - 2 * (int) pow((double) rT[1], (double) 2) + (int) pow((double) rT[2], (double) 2) + PERTURBAZIONE) * m[1] + 3 * (rR[1] - rT[1]) * (-m[0] * rR[0] + m[0] * rT[0] - m[2] * rR[2] + m[2] * rT[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (-2 * rR[1] + 2 * rT[1]);
    HMtx[14] = -(double) ((-2 * rR[2] + 2 * rT[2]) * m[1] + 3 * (rR[1] - rT[1]) * m[2]) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.4e1 + 0.5e1 / 0.8e1 * (double) (((int) pow((double) rR[0], (double) 2) - 2 * rR[0] * rT[0] - 2 * (int) pow((double) rR[1], (double) 2) + 4 * rR[1] * rT[1] + (int) pow((double) rR[2], (double) 2) - 2 * rR[2] * rT[2] + (int) pow((double) rT[0], (double) 2) - 2 * (int) pow((double) rT[1], (double) 2) + (int) pow((double) rT[2], (double) 2) + PERTURBAZIONE) * m[1] + 3 * (rR[1] - rT[1]) * (-m[0] * rR[0] + m[0] * rT[0] - m[2] * rR[2] + m[2] * rT[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (-2 * rR[2] + 2 * rT[2]);
    HMtx[15] = -0.3e1 / 0.4e1 * (double) (rR[1] - rT[1]) * (double) (-rR[0] + rT[0]) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1);
    HMtx[16] = -(double) ((int) pow((double) rR[0], (double) 2) - 2 * rR[0] * rT[0] - 2 * (int) pow((double) rR[1], (double) 2) + 4 * rR[1] * rT[1] + (int) pow((double) rR[2], (double) 2) - 2 * rR[2] * rT[2] + (int) pow((double) rT[0], (double) 2) - 2 * (int) pow((double) rT[1], (double) 2) + (int) pow((double) rT[2], (double) 2) + PERTURBAZIONE) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.4e1;
    HMtx[17] = -0.3e1 / 0.4e1 * (double) (rR[1] - rT[1]) * (double) (rT[2] - rR[2]) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1);
    HMtx[18] = ((double) ((-rR[0] + rT[0]) * m[2]) - 0.3e1 / 0.2e1 * (double) m[0] * (double) (rT[2] - rR[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.2e1 - 0.5e1 / 0.4e1 * (((double) (int) pow((double) rT[2], (double) 2) - (double) (2 * rR[2] * rT[2]) - (double) (int) pow((double) rR[0], (double) 2) / 0.2e1 + (double) (rR[0] * rT[0]) - (double) (int) pow((double) rR[1], (double) 2) / 0.2e1 + (double) (rR[1] * rT[1]) + (double) (int) pow((double) rR[2], (double) 2) - (double) (int) pow((double) rT[0], (double) 2) / 0.2e1 - (double) (int) pow((double) rT[1], (double) 2) / 0.2e1 - (double) PERTURBAZIONE / 0.2e1) * (double) m[2] - 0.3e1 / 0.2e1 * (double) (m[0] * rR[0] - m[0] * rT[0] + m[1] * rR[1] - m[1] * rT[1]) * (double) (rT[2] - rR[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (2 * rR[0] - 2 * rT[0]);
    HMtx[19] = ((double) ((-rR[1] + rT[1]) * m[2]) - 0.3e1 / 0.2e1 * (double) m[1] * (double) (rT[2] - rR[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.2e1 - 0.5e1 / 0.4e1 * (((double) (int) pow((double) rT[2], (double) 2) - (double) (2 * rR[2] * rT[2]) - (double) (int) pow((double) rR[0], (double) 2) / 0.2e1 + (double) (rR[0] * rT[0]) - (double) (int) pow((double) rR[1], (double) 2) / 0.2e1 + (double) (rR[1] * rT[1]) + (double) (int) pow((double) rR[2], (double) 2) - (double) (int) pow((double) rT[0], (double) 2) / 0.2e1 - (double) (int) pow((double) rT[1], (double) 2) / 0.2e1 - (double) PERTURBAZIONE / 0.2e1) * (double) m[2] - 0.3e1 / 0.2e1 * (double) (m[0] * rR[0] - m[0] * rT[0] + m[1] * rR[1] - m[1] * rT[1]) * (double) (rT[2] - rR[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (2 * rR[1] - 2 * rT[1]);
    HMtx[20] = ((double) ((2 * rR[2] - 2 * rT[2]) * m[2]) + 0.3e1 / 0.2e1 * (double) m[0] * (double) rR[0] - 0.3e1 / 0.2e1 * (double) m[0] * (double) rT[0] + 0.3e1 / 0.2e1 * (double) m[1] * (double) rR[1] - 0.3e1 / 0.2e1 * (double) m[1] * (double) rT[1]) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.2e1 - 0.5e1 / 0.4e1 * (((double) (int) pow((double) rT[2], (double) 2) - (double) (2 * rR[2] * rT[2]) - (double) (int) pow((double) rR[0], (double) 2) / 0.2e1 + (double) (rR[0] * rT[0]) - (double) (int) pow((double) rR[1], (double) 2) / 0.2e1 + (double) (rR[1] * rT[1]) + (double) (int) pow((double) rR[2], (double) 2) - (double) (int) pow((double) rT[0], (double) 2) / 0.2e1 - (double) (int) pow((double) rT[1], (double) 2) / 0.2e1 - (double) PERTURBAZIONE / 0.2e1) * (double) m[2] - 0.3e1 / 0.2e1 * (double) (m[0] * rR[0] - m[0] * rT[0] + m[1] * rR[1] - m[1] * rT[1]) * (double) (rT[2] - rR[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (2 * rR[2] - 2 * rT[2]);
    HMtx[21] = ((double) ((rR[0] - rT[0]) * m[2]) + 0.3e1 / 0.2e1 * (double) m[0] * (double) (rT[2] - rR[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.2e1 - 0.5e1 / 0.4e1 * (((double) (int) pow((double) rT[2], (double) 2) - (double) (2 * rR[2] * rT[2]) - (double) (int) pow((double) rR[0], (double) 2) / 0.2e1 + (double) (rR[0] * rT[0]) - (double) (int) pow((double) rR[1], (double) 2) / 0.2e1 + (double) (rR[1] * rT[1]) + (double) (int) pow((double) rR[2], (double) 2) - (double) (int) pow((double) rT[0], (double) 2) / 0.2e1 - (double) (int) pow((double) rT[1], (double) 2) / 0.2e1 - (double) PERTURBAZIONE / 0.2e1) * (double) m[2] - 0.3e1 / 0.2e1 * (double) (m[0] * rR[0] - m[0] * rT[0] + m[1] * rR[1] - m[1] * rT[1]) * (double) (rT[2] - rR[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (-2 * rR[0] + 2 * rT[0]);
    HMtx[22] = ((double) ((rR[1] - rT[1]) * m[2]) + 0.3e1 / 0.2e1 * (double) m[1] * (double) (rT[2] - rR[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.2e1 - 0.5e1 / 0.4e1 * (((double) (int) pow((double) rT[2], (double) 2) - (double) (2 * rR[2] * rT[2]) - (double) (int) pow((double) rR[0], (double) 2) / 0.2e1 + (double) (rR[0] * rT[0]) - (double) (int) pow((double) rR[1], (double) 2) / 0.2e1 + (double) (rR[1] * rT[1]) + (double) (int) pow((double) rR[2], (double) 2) - (double) (int) pow((double) rT[0], (double) 2) / 0.2e1 - (double) (int) pow((double) rT[1], (double) 2) / 0.2e1 - (double) PERTURBAZIONE / 0.2e1) * (double) m[2] - 0.3e1 / 0.2e1 * (double) (m[0] * rR[0] - m[0] * rT[0] + m[1] * rR[1] - m[1] * rT[1]) * (double) (rT[2] - rR[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (-2 * rR[1] + 2 * rT[1]);
    HMtx[23] = ((double) ((-2 * rR[2] + 2 * rT[2]) * m[2]) - 0.3e1 / 0.2e1 * (double) m[0] * (double) rR[0] + 0.3e1 / 0.2e1 * (double) m[0] * (double) rT[0] - 0.3e1 / 0.2e1 * (double) m[1] * (double) rR[1] + 0.3e1 / 0.2e1 * (double) m[1] * (double) rT[1]) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.2e1 - 0.5e1 / 0.4e1 * (((double) (int) pow((double) rT[2], (double) 2) - (double) (2 * rR[2] * rT[2]) - (double) (int) pow((double) rR[0], (double) 2) / 0.2e1 + (double) (rR[0] * rT[0]) - (double) (int) pow((double) rR[1], (double) 2) / 0.2e1 + (double) (rR[1] * rT[1]) + (double) (int) pow((double) rR[2], (double) 2) - (double) (int) pow((double) rT[0], (double) 2) / 0.2e1 - (double) (int) pow((double) rT[1], (double) 2) / 0.2e1 - (double) PERTURBAZIONE / 0.2e1) * (double) m[2] - 0.3e1 / 0.2e1 * (double) (m[0] * rR[0] - m[0] * rT[0] + m[1] * rR[1] - m[1] * rT[1]) * (double) (rT[2] - rR[2])) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.7e1 / 0.2e1) * (double) (-2 * rR[2] + 2 * rT[2]);
    HMtx[24] = -0.3e1 / 0.4e1 * M_1_PI * (double) (rR[0] - rT[0]) * (double) (rT[2] - rR[2]) * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1);
    HMtx[25] = -0.3e1 / 0.4e1 * (double) (rR[1] - rT[1]) * (double) (rT[2] - rR[2]) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1);
    HMtx[26] = ((double) (int) pow((double) rT[2], (double) 2) - (double) (2 * rR[2] * rT[2]) - (double) (int) pow((double) rR[0], (double) 2) / 0.2e1 + (double) (rR[0] * rT[0]) - (double) (int) pow((double) rR[1], (double) 2) / 0.2e1 + (double) (rR[1] * rT[1]) + (double) (int) pow((double) rR[2], (double) 2) - (double) (int) pow((double) rT[0], (double) 2) / 0.2e1 - (double) (int) pow((double) rT[1], (double) 2) / 0.2e1 - (double) PERTURBAZIONE / 0.2e1) * M_1_PI * pow((double) ((int) pow((double) (rR[0] - rT[0]), (double) 2) + (int) pow((double) (rR[1] - rT[1]), (double) 2) + (int) pow((double) (rR[2] - rT[2]), (double) 2) + PERTURBAZIONE), -0.5e1 / 0.2e1) / 0.2e1;
}

/* mexFunction - Entry point for Matlab */
void mexFunction( int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[] ) {
  
  /* 
   * nhls - number of elements as output mxArrays
   * plhs - pointer to output elements mxArrays
   * nrhs - number of input elements mxArrays
   * prhs - pointer to output elements mxArrays
   */
    
  double *HMtx, *rR, *rT, *m;
  
  
  /* Check for proper number of arguments. */
  if(nrhs!=3) {
    mexErrMsgIdAndTxt( "MATLAB:HMtx:invalidNumInputs",
            "3 inputs required: (rR, rT, m)");
  } else if(nlhs>1) {
    mexErrMsgIdAndTxt( "MATLAB:Hmtx:invalidNumOutputs",
            "Too many output arguments.");
  }
  
  /* Create matrix for the return argument Hfield */
  plhs[0] = mxCreateDoubleMatrix((mwSize)3, (mwSize)9, mxREAL);
  
  /* Assign pointers to each input and output. */
  rR    = mxGetPr(prhs[0]);
  rT    = mxGetPr(prhs[1]);
  m     = mxGetPr(prhs[2]);
  HMtx  = mxGetPr(plhs[0]);
  
  /* Call the timestwo subroutine. */
  HMtx_fnc(HMtx, rR, rT, m);
}
